### ISSUE TITLE
Suggestion to change workflow

### ISSUE THREAD

**Issue by dan-delion** [CS2103-AY1819S1-W12-1/main#32]
Given the size of the team and the redundancy of forks, we should probably consider changing from **forking workflow** to **feature branch workflow**.

Thoughts?

**Comment by dan-delion** [comment]
What do you mean by ``import the whole project''?

**Comment by Swiftkage** [comment]
My current copy is from my own fork

**Comment by dan-delion** [comment]
So I take it you only need to clone and import it right?

My point was that we aren't working on significantly separated features, so far the workflow we follow is:

- Fork from upstream
- Merge updates on upstream into fork when necessary
- Push changes to fork
- Make PR from fork branch into upstream branch

I don't see how we are making use of the forking workflow anyway, it feels redundant having a separate fork that we have to update manually whenever there are changes in the upstream repo.

As an added bonus, directly working on the upstream repo means we only need to take care of one clone, which should appeal to your (and my) ``laziness''.
